name: Deploy Blog to Server

on:
  push:
    branches: [main, redesign]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Build Astro Site
        run: |
          pnpm install --frozen-lockfile
          pnpm build
      - name: Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './dist/*'
          remote_path: ${{ secrets.SFTP_PATH }}
