name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i -g pnpm
      - run: pnpm
      - run: pnpm run build

      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "dist/*"
          target: "/home/github/blog"
          overwrite: true
          rm: true
          strip_components: 1
